### ISSUE TITLE
High problem!

### ISSUE THREAD

**Issue by TDMario** [ac-webdesign/m133-queue-stack#1]
Hello.
Im buyer of progrem. I have no understanding!!
If i klick button queue and have stuff in window stack, than will delete from stack and not will create new in queue.
it dont work?
please help
- Mario

**Comment by TDMario** [comment]
Where are my helping??

**Comment by TDMario** [comment]
i want my money back

**Comment by ac-webdesign** [comment]
Is fixed in the newest commit. Thanks.
